baseURL = 'https://ilan-stern.github.io/my-site/'
languageCode = 'en-au'
title = 'Bit-by-Bit'
theme = 'hugo-theme-m10c'

[params]
  author = "Ilan Stern"
  description = "This is a portfolio to follow my Cyber Career advancements - Bit-by-Bit | Currently SOC Analyst"
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-LinkedIn"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ilan-stern-baa413192/"

# Red theme
 [params.style]
   darkestColor = "#d1001f"
   darkColor = "#000000"
   lightColor = "#d6d6d6"
   lightestColor = "#d3d3d3"
   primaryColor = "#ffffff"
