baseURL = 'https://lean.dev/'
languageCode = 'en-au'
title = 'Bit-by-Bit'
theme = 'hugo-theme-m10c'
description = 'This is a portfolio to follow my Cyber Career advancements - Bit-by-Bit | Currently SOC Analyst'
